### ISSUE TITLE
libui: Fatal error: expecting ": EXPR" in ternary expression

### ISSUE THREAD

**Issue by matheusfaustino** [ircmaxell/php-c-parser#6]
Hi, I'm here again, sorry... 
I'm trying to use your lib with the project [libui](https://github.com/andlabs/libui) and then, when I try to parse the headers it throws this error:
```
Fatal error: Uncaught LogicException: Syntax Error: expecting ": EXPR" in ternary expression in /vendor/ircmaxell/php-c-parser/lib/Context.php:334
```
I found that it's cause by this expression in this file `/usr/include/features.h` [see here](https://gist.github.com/matheusfaustino/58c611d596ec027f8849a7c382472aac):
```
#if defined __cplusplus ? __cplusplus >= 201402L : defined __USE_ISOC11
# define __GLIBC_USE_DEPRECATED_GETS 0
#else
# define __GLIBC_USE_DEPRECATED_GETS 1
#endif
```

My code:
```php
(new FFIMe('/usr/lib/libui.so.0', ['/usr/include/glib-2.0/', '/usr/lib/x86_64-linux-gnu/glib-2.0/include/']))
    ->include('/usr/include/gtk-2.0/gtk/gtk.h')
    ->include('/usr/include/ui.h')
    ->include('/usr/include/ui_unix.h')
    ->codeGen('libui\\libui', __DIR__ . '/ui.php');
```
I tried to change the `evaluateInternal` function but, without success, yet. I tried to change the logic with the `$single` var but, nothing yet. 
I'd like to know if you could help me with this, please.

Thanks in advance.

**Comment by matheusfaustino** [comment]
Well, I will try to follow the lead you gave me and see if the modifications work. Thank you for your time ^^

**Comment by matheusfaustino** [comment]
Would it be possible to make the parser get a modified version of the header, but respecting the path found?

For instance: it finds that it should parse the header features.h (located in: /usr/include/) but instead of getting the real header (/usr/include/features.h) , it would get a modified version from the project's folder (<home>/ffi-project/features.h). 

what do you think about it? It could be a workaround for it.

**Comment by silverfoxy** [comment]
@matheusfaustino any progress on your end?
I am trying to expand the macros and then use the parser to work around the ternary operator parsing issue, but no luck yet (I run into other parsing errors).

**Comment by hktr92** [comment]
i ran into this same issue when trying out your ffime package and output libc into php file on ubuntu 20.04
